import "./featured.scss";
import SchoolIcon from "@mui/icons-material/School";
import { CircularProgressbar } from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import KeyboardArrowUpOutlinedIcon from "@mui/icons-material/KeyboardArrowUpOutlined";

const Featured = () => {
  // Replace this school-related data with your own
  const schoolData = {
    name: "Maplewood High School",
    totalRevenue: "$25,000",
    totalStudents: 500,
    targetRevenue: "$30,000",
    lastWeekRevenue: "$28,000",
    lastMonthRevenue: "$27,000",
  };

  return (
    <div className="featured">
      <div className="top">
        <SchoolIcon fontSize="large" />
        <h1 className="title">{schoolData.name}</h1>
      </div>
      <div className="bottom">
        <div className="featuredChart">
          <CircularProgressbar
            value={(parseInt(schoolData.totalRevenue.slice(1)) / 60) * 100} // Calculate percentage
            text={schoolData.totalRevenue}
            strokeWidth={5}
          />
        </div>
        <p className="title">Total Revenue</p>
        <p className="amount">{schoolData.totalRevenue}</p>
        <p className="desc">
          Total revenue generated by the school. Target:{" "}
          {schoolData.targetRevenue}
        </p>
        <div className="summary">
          <div className="item">
            <div className="itemTitle">Total Students</div>
            <div className="itemResult positive">
              <KeyboardArrowUpOutlinedIcon fontSize="small" />
              <div className="resultAmount">{schoolData.totalStudents}</div>
            </div>
          </div>
          <div className="item">
            <div className="itemTitle">Last Week Revenue</div>
            <div className="itemResult positive">
              <KeyboardArrowUpOutlinedIcon fontSize="small" />
              <div className="resultAmount">{schoolData.lastWeekRevenue}</div>
            </div>
          </div>
          <div className="item">
            <div className="itemTitle">Last Month Revenue</div>
            <div className="itemResult positive">
              <KeyboardArrowUpOutlinedIcon fontSize="small" />
              <div className="resultAmount">{schoolData.lastMonthRevenue}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Featured;
